#Clone Git Repository
---
- name: Clone a Git repository
  hosts: appservers
  become: yes
  tasks:
    - name: Clone Git repo
      git:
        repo: https://github.com/example/repo.git
        dest: /opt/myapp
